"""The UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant, callback
from homeassistant.exceptions import ConfigEntryNotReady
from homeassistant.helpers import (
    device_registry as dr,
    entity_registry as er,
    issue_registry as ir,
)
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import StationMeta, UbaLqiApiClient, UbaLqiError
from .const import (
    CONF_LOCATION_SOURCE,
    CONF_RADIUS_KM,
    CONF_STATIONS,
    CONF_UPDATE_INTERVAL,
    DEFAULT_RADIUS_KM,
    DEFAULT_UPDATE_INTERVAL_MINUTES,
    DISCOVERY_WINDOW_HOURS,
    DOMAIN,
    ISSUE_STATION_SILENT,
    LOCATION_SOURCE_HOME,
    MIN_UPDATE_INTERVAL_MINUTES,
)
from .coordinator import UbaLqiCoordinator
from .util import haversine_km

_LOGGER = logging.getLogger(__name__)

PLATFORMS: list[Platform] = [Platform.SENSOR]

type UbaLqiConfigEntry = ConfigEntry[UbaLqiCoordinator]


async def async_setup_entry(hass: HomeAssistant, entry: UbaLqiConfigEntry) -> bool:
    """Set up UBA LQI from a config entry."""
    client = UbaLqiApiClient(async_get_clientsession(hass))

    await _async_ensure_station_metadata(hass, entry, client)

    coordinator = UbaLqiCoordinator(hass, entry, client)
    await coordinator.async_config_entry_first_refresh()
    entry.runtime_data = coordinator

    _async_remove_stale_registry_entries(hass, entry)

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))
    return True


async def async_unload_entry(hass: HomeAssistant, entry: UbaLqiConfigEntry) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)


async def _async_update_listener(hass: HomeAssistant, entry: UbaLqiConfigEntry) -> None:
    """Reload the entry when options change."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_migrate_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Migrate old config entries to the current schema."""
    if entry.version > 2:
        # Eintrag stammt aus einer neueren Version dieser Integration.
        return False

    if entry.version == 1:
        old = {**entry.data, **entry.options}
        home_lat = old.get("latitude")
        home_lon = old.get("longitude")
        stations: dict[str, dict[str, Any]] = {}
        for station_id in old.get("selected_stations", []):
            details = old.get("station_details", {}).get(str(station_id), {})
            latitude = details.get("latitude")
            longitude = details.get("longitude")
            distance = None
            if (
                home_lat is not None
                and home_lon is not None
                and latitude is not None
                and longitude is not None
            ):
                distance = round(
                    haversine_km(
                        float(home_lat),
                        float(home_lon),
                        float(latitude),
                        float(longitude),
                    ),
                    2,
                )
            stations[str(station_id)] = {
                "code": details.get("code"),
                "name": details.get("name") or str(station_id),
                "city": details.get("city"),
                "latitude": latitude,
                "longitude": longitude,
                "setting": details.get("station_setting_name"),
                "station_type": details.get("station_type_name"),
                "distance_km": distance,
                # None -> wird beim nächsten Setup einmalig per API ermittelt.
                "components": None,
            }
        if not stations:
            _LOGGER.error(
                "Cannot migrate entry %s: no stations found in old data", entry.title
            )
            return False
        # Nach Entfernung sortieren (Anzeige-Reihenfolge; der kombinierte
        # Sensor sortiert zur Laufzeit selbst nach Entfernung).
        stations = dict(
            sorted(
                stations.items(),
                key=lambda item: (
                    item[1]["distance_km"] is None,
                    item[1]["distance_km"] or 0.0,
                ),
            )
        )
        data = {
            CONF_LOCATION_SOURCE: old.get("location_source", LOCATION_SOURCE_HOME),
            "latitude": old.get("latitude"),
            "longitude": old.get("longitude"),
            CONF_RADIUS_KM: old.get("search_radius_km", DEFAULT_RADIUS_KM),
            CONF_STATIONS: stations,
        }
        interval = int(
            old.get("scan_interval_minutes", DEFAULT_UPDATE_INTERVAL_MINUTES)
        )
        options = {
            CONF_UPDATE_INTERVAL: max(interval, MIN_UPDATE_INTERVAL_MINUTES),
        }
        await _async_migrate_v1_unique_ids(hass, entry)
        hass.config_entries.async_update_entry(
            entry, data=data, options=options, version=2, minor_version=1
        )
        _LOGGER.info("Migrated config entry %s to version 2", entry.title)
    elif entry.minor_version != 1:
        # Ohne Angleich der Minor-Version liefe die Migration bei jedem Start.
        hass.config_entries.async_update_entry(entry, minor_version=1)

    return True


# Umbenannte Sensoren der Version 1: Entity-IDs, Anpassungen und Historie
# bleiben erhalten. Nicht gelistete v1-Sensoren (measurement_start,
# data_completeness) entfallen ersatzlos und werden beim Setup bereinigt.
_V1_UNIQUE_ID_RENAMES = {
    "lqi_label": "lqi",
    "measurement_end": "last_measurement",
}


async def _async_migrate_v1_unique_ids(
    hass: HomeAssistant, entry: ConfigEntry
) -> None:
    entity_registry = er.async_get(hass)

    @callback
    def _migrate(entity_entry: er.RegistryEntry) -> dict[str, str] | None:
        for old_suffix, new_suffix in _V1_UNIQUE_ID_RENAMES.items():
            if not entity_entry.unique_id.endswith(f"_{old_suffix}"):
                continue
            new_unique_id = (
                entity_entry.unique_id.removesuffix(old_suffix) + new_suffix
            )
            if entity_registry.async_get_entity_id(
                "sensor", DOMAIN, new_unique_id
            ):
                return None  # Ziel existiert bereits; das Alte wird bereinigt.
            return {"new_unique_id": new_unique_id}
        return None

    await er.async_migrate_entries(hass, entry.entry_id, _migrate)


async def _async_ensure_station_metadata(
    hass: HomeAssistant, entry: UbaLqiConfigEntry, client: UbaLqiApiClient
) -> None:
    """Ergänzt fehlende Stationsmetadaten (z. B. nach Migration) einmalig.

    Zwei Lücken können v1-Einträge hinterlassen: fehlende Entfernungen (der
    kombinierte Index braucht sie, um die nächstgelegene Station je Komponente
    zu bestimmen) und fehlende Komponentenlisten. Entitäten entstehen aus
    diesen gespeicherten Metadaten - nicht aus der ersten API-Antwort, damit
    keine Entität fehlt, wenn eine Komponente gerade "hinkt".

    Der Entfernungs-Nachtrag ist weich: Schlägt die Stationsliste fehl, läuft
    das Setup ohne Entfernungen weiter (die Speicher-Reihenfolge bleibt dann
    das Fallback). Die Komponenten-Ermittlung bleibt hart (ConfigEntryNotReady).

    Bewusst: Eine Station, die im Discovery-Fenster nichts lieferte
    (``components: []``), wird bei jedem weiteren Setup erneut befragt, damit
    ihre Entitäten entstehen, sobald sie wieder meldet. Kostet einen
    API-Aufruf je Start und stummer Station.
    """
    stations: dict[str, dict[str, Any]] = entry.data[CONF_STATIONS]
    home_lat = entry.data.get("latitude")
    home_lon = entry.data.get("longitude")
    needs_geo = (
        home_lat is not None
        and home_lon is not None
        and any(config.get("distance_km") is None for config in stations.values())
    )
    needs_components = not all(
        config.get("components") for config in stations.values()
    )
    if not needs_geo and not needs_components:
        return

    new_stations = {
        station_id: dict(config) for station_id, config in stations.items()
    }

    if needs_geo and home_lat is not None and home_lon is not None:
        meta: dict[str, StationMeta] | None = None
        if any(
            config.get("distance_km") is None
            and (config.get("latitude") is None or config.get("longitude") is None)
            for config in new_stations.values()
        ):
            try:
                meta = await client.async_get_stations(
                    hours_back=DISCOVERY_WINDOW_HOURS
                )
            except UbaLqiError as err:
                _LOGGER.warning(
                    "Could not fetch the station list to determine distances, "
                    "keeping the stored station order: %s",
                    err,
                )
        for station_id, config in new_stations.items():
            if config.get("distance_km") is not None:
                continue
            latitude = config.get("latitude")
            longitude = config.get("longitude")
            if (latitude is None or longitude is None) and meta is not None:
                station = meta.get(station_id)
                if station is not None:
                    latitude = station.latitude
                    longitude = station.longitude
                    config["latitude"] = latitude
                    config["longitude"] = longitude
            if latitude is not None and longitude is not None:
                config["distance_km"] = round(
                    haversine_km(
                        float(home_lat),
                        float(home_lon),
                        float(latitude),
                        float(longitude),
                    ),
                    2,
                )
        new_stations = dict(
            sorted(
                new_stations.items(),
                key=lambda item: (
                    item[1]["distance_km"] is None,
                    item[1]["distance_km"] or 0.0,
                ),
            )
        )

    for station_id, config in new_stations.items():
        if config.get("components"):
            continue
        try:
            air = await client.async_get_air_quality(
                station_id, hours_back=DISCOVERY_WINDOW_HOURS
            )
        except UbaLqiError as err:
            raise ConfigEntryNotReady(
                f"Could not determine components of station {station_id}: {err}"
            ) from err
        components = sorted(air.components)
        if not components:
            _LOGGER.warning(
                "Station %s delivered no data within %d hours; "
                "its sensors will stay unavailable until it reports again",
                station_id,
                DISCOVERY_WINDOW_HOURS,
            )
        config["components"] = components

    if list(new_stations.items()) != list(stations.items()):
        hass.config_entries.async_update_entry(
            entry, data={**entry.data, CONF_STATIONS: new_stations}
        )


def _async_remove_stale_registry_entries(
    hass: HomeAssistant, entry: UbaLqiConfigEntry
) -> None:
    """Remove devices and entities that no longer match the configuration."""
    from .sensor import expected_unique_ids  # zyklusfreier lokaler Import

    expected_devices = {(DOMAIN, station_id) for station_id in entry.data[CONF_STATIONS]}
    expected_devices.add((DOMAIN, f"{entry.entry_id}_combined"))

    device_registry = dr.async_get(hass)
    for device in dr.async_entries_for_config_entry(device_registry, entry.entry_id):
        if not device.identifiers & expected_devices:
            device_registry.async_update_device(
                device.id, remove_config_entry_id=entry.entry_id
            )

    expected = expected_unique_ids(entry)
    entity_registry = er.async_get(hass)
    for entity in er.async_entries_for_config_entry(entity_registry, entry.entry_id):
        if entity.unique_id not in expected:
            entity_registry.async_remove(entity.entity_id)

    # Repair Issues von Stationen löschen, die (über alle Einträge hinweg)
    # nicht mehr konfiguriert sind - z. B. nach einem Reconfigure.
    configured: set[str] = set()
    for other in hass.config_entries.async_entries(DOMAIN):
        configured.update(other.data.get(CONF_STATIONS, {}))
    issue_registry = ir.async_get(hass)
    prefix = f"{ISSUE_STATION_SILENT}_"
    for domain, issue_id in list(issue_registry.issues):
        if (
            domain == DOMAIN
            and issue_id.startswith(prefix)
            and issue_id.removeprefix(prefix) not in configured
        ):
            ir.async_delete_issue(hass, DOMAIN, issue_id)
