"""The UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import ConfigEntryNotReady
from homeassistant.helpers import device_registry as dr, entity_registry as er
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import UbaLqiApiClient, UbaLqiError
from .const import (
    CONF_LOCATION_SOURCE,
    CONF_RADIUS_KM,
    CONF_STATIONS,
    CONF_UPDATE_INTERVAL,
    DEFAULT_RADIUS_KM,
    DEFAULT_UPDATE_INTERVAL_MINUTES,
    DISCOVERY_WINDOW_HOURS,
    DOMAIN,
    LOCATION_SOURCE_HOME,
    MIN_UPDATE_INTERVAL_MINUTES,
)
from .coordinator import UbaLqiCoordinator
from .util import haversine_km

_LOGGER = logging.getLogger(__name__)

PLATFORMS: list[Platform] = [Platform.SENSOR]

type UbaLqiConfigEntry = ConfigEntry[UbaLqiCoordinator]


async def async_setup_entry(hass: HomeAssistant, entry: UbaLqiConfigEntry) -> bool:
    """Set up UBA LQI from a config entry."""
    client = UbaLqiApiClient(async_get_clientsession(hass))

    await _async_ensure_station_components(hass, entry, client)

    coordinator = UbaLqiCoordinator(hass, entry, client)
    await coordinator.async_config_entry_first_refresh()
    entry.runtime_data = coordinator

    _async_remove_stale_registry_entries(hass, entry)

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))
    return True


async def async_unload_entry(hass: HomeAssistant, entry: UbaLqiConfigEntry) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)


async def _async_update_listener(hass: HomeAssistant, entry: UbaLqiConfigEntry) -> None:
    """Reload the entry when options change."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_migrate_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Migrate old config entries to the current schema."""
    if entry.version > 2:
        # Eintrag stammt aus einer neueren Version dieser Integration.
        return False

    if entry.version == 1:
        old = {**entry.data, **entry.options}
        home_lat = old.get("latitude")
        home_lon = old.get("longitude")
        stations: dict[str, dict[str, Any]] = {}
        for station_id in old.get("selected_stations", []):
            details = old.get("station_details", {}).get(str(station_id), {})
            latitude = details.get("latitude")
            longitude = details.get("longitude")
            distance = None
            if (
                home_lat is not None
                and home_lon is not None
                and latitude is not None
                and longitude is not None
            ):
                distance = round(
                    haversine_km(
                        float(home_lat),
                        float(home_lon),
                        float(latitude),
                        float(longitude),
                    ),
                    2,
                )
            stations[str(station_id)] = {
                "code": details.get("code"),
                "name": details.get("name") or str(station_id),
                "city": details.get("city"),
                "latitude": latitude,
                "longitude": longitude,
                "setting": details.get("station_setting_name"),
                "station_type": details.get("station_type_name"),
                "distance_km": distance,
                # None -> wird beim nächsten Setup einmalig per API ermittelt.
                "components": None,
            }
        if not stations:
            _LOGGER.error(
                "Cannot migrate entry %s: no stations found in old data", entry.title
            )
            return False
        # Nach Entfernung sortieren: beim kombinierten Index gewinnt je
        # Komponente die zuerst gelistete (nächstgelegene) Station.
        stations = dict(
            sorted(
                stations.items(),
                key=lambda item: (
                    item[1]["distance_km"] is None,
                    item[1]["distance_km"] or 0.0,
                ),
            )
        )
        data = {
            CONF_LOCATION_SOURCE: old.get("location_source", LOCATION_SOURCE_HOME),
            "latitude": old.get("latitude"),
            "longitude": old.get("longitude"),
            CONF_RADIUS_KM: old.get("search_radius_km", DEFAULT_RADIUS_KM),
            CONF_STATIONS: stations,
        }
        interval = int(
            old.get("scan_interval_minutes", DEFAULT_UPDATE_INTERVAL_MINUTES)
        )
        options = {
            CONF_UPDATE_INTERVAL: max(interval, MIN_UPDATE_INTERVAL_MINUTES),
        }
        hass.config_entries.async_update_entry(
            entry, data=data, options=options, version=2
        )
        _LOGGER.info("Migrated config entry %s to version 2", entry.title)

    return True


async def _async_ensure_station_components(
    hass: HomeAssistant, entry: UbaLqiConfigEntry, client: UbaLqiApiClient
) -> None:
    """Ermittelt fehlende Komponentenlisten (z. B. nach Migration) einmalig.

    Entitäten entstehen aus diesen gespeicherten Metadaten - nicht aus der
    ersten API-Antwort, damit keine Entität fehlt, wenn eine Komponente
    gerade "hinkt".
    """
    stations: dict[str, dict[str, Any]] = entry.data[CONF_STATIONS]
    if all(config.get("components") for config in stations.values()):
        return

    new_stations: dict[str, dict[str, Any]] = {}
    for station_id, config in stations.items():
        if config.get("components"):
            new_stations[station_id] = config
            continue
        try:
            air = await client.async_get_air_quality(
                station_id, hours_back=DISCOVERY_WINDOW_HOURS
            )
        except UbaLqiError as err:
            raise ConfigEntryNotReady(
                f"Could not determine components of station {station_id}: {err}"
            ) from err
        components = sorted(air.components)
        if not components:
            _LOGGER.warning(
                "Station %s delivered no data within %d hours; "
                "its sensors will stay unavailable until it reports again",
                station_id,
                DISCOVERY_WINDOW_HOURS,
            )
        new_stations[station_id] = {**config, "components": components}

    hass.config_entries.async_update_entry(
        entry, data={**entry.data, CONF_STATIONS: new_stations}
    )


def _async_remove_stale_registry_entries(
    hass: HomeAssistant, entry: UbaLqiConfigEntry
) -> None:
    """Remove devices and entities that no longer match the configuration."""
    from .sensor import expected_unique_ids  # zyklusfreier lokaler Import

    expected_devices = {(DOMAIN, station_id) for station_id in entry.data[CONF_STATIONS]}
    expected_devices.add((DOMAIN, f"{entry.entry_id}_combined"))

    device_registry = dr.async_get(hass)
    for device in dr.async_entries_for_config_entry(device_registry, entry.entry_id):
        if not device.identifiers & expected_devices:
            device_registry.async_update_device(
                device.id, remove_config_entry_id=entry.entry_id
            )

    expected = expected_unique_ids(entry)
    entity_registry = er.async_get(hass)
    for entity in er.async_entries_for_config_entry(entity_registry, entry.entry_id):
        if entity.unique_id not in expected:
            entity_registry.async_remove(entity.entity_id)
