"""Async client for the Umweltbundesamt air data API v4.

Frei von Home-Assistant-Abhängigkeiten: Die aiohttp-Session wird injiziert,
alle Zeitstempel werden als feste MEZ (UTC+1) geparst und als UTC zurückgegeben.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

from aiohttp import ClientError, ClientSession, ClientTimeout

from .const import API_BASE_URL, API_TIMEOUT, API_TZ

_TIME_FORMAT = "%Y-%m-%d %H:%M:%S"


class UbaLqiError(Exception):
    """Base error for the UBA LQI API."""


class UbaLqiConnectionError(UbaLqiError):
    """The API could not be reached."""


class UbaLqiResponseError(UbaLqiError):
    """The API responded with an unexpected payload."""


@dataclass(frozen=True, slots=True)
class StationMeta:
    """Metadata of a measuring station."""

    station_id: str
    code: str
    name: str
    city: str | None
    latitude: float | None
    longitude: float | None
    setting: str | None
    station_type: str | None
    street: str | None
    zip_code: str | None
    active_from: str | None
    active_to: str | None


@dataclass(frozen=True, slots=True)
class ComponentValue:
    """Newest reading of a single component at a station."""

    component_id: int
    value: float | None
    index: int | None
    threshold_progress: float | None
    start: datetime
    end: datetime


@dataclass(frozen=True, slots=True)
class StationAirQuality:
    """Newest air quality readings of a station.

    ``components`` enthält je Komponente den jüngsten Wert im Abfragefenster,
    auch wenn dieser aus einer älteren Stunde stammt als der jüngste Datensatz
    ("hinkende" Komponenten gehen nicht verloren).
    """

    station_id: str
    components: dict[int, ComponentValue]
    total_index: int | None
    newest_start: datetime | None
    newest_end: datetime | None
    all_components_reported: bool | None


class UbaLqiApiClient:
    """Minimal async client for the endpoints used by this integration."""

    def __init__(self, session: ClientSession, base_url: str = API_BASE_URL) -> None:
        self._session = session
        self._base_url = base_url.rstrip("/")

    async def _async_get(self, path: str, params: dict[str, str]) -> dict[str, Any]:
        url = f"{self._base_url}/{path}"
        try:
            async with self._session.get(
                url,
                params=params,
                headers={"Accept": "application/json"},
                timeout=ClientTimeout(total=API_TIMEOUT),
            ) as response:
                response.raise_for_status()
                data: Any = await response.json(content_type=None)
        except TimeoutError as err:
            raise UbaLqiConnectionError(f"Timeout while calling {url}") from err
        except ClientError as err:
            raise UbaLqiConnectionError(f"Error calling {url}: {err}") from err
        except ValueError as err:
            raise UbaLqiResponseError(f"Invalid JSON from {url}") from err
        if not isinstance(data, dict):
            raise UbaLqiResponseError(f"Unexpected payload type from {url}")
        return data

    async def async_get_stations(self, *, hours_back: int) -> dict[str, StationMeta]:
        """Return all stations that delivered air quality data within the window.

        Mit Datumsfenster liefert die v4-API nur die aktiven Stationen
        (~420 statt ~2400). Enthält das Fenster keine Messdaten (Datenausfall
        beim UBA), fehlt ``stations`` in der Antwort komplett. Wird
        ausschließlich im Config Flow aufgerufen.
        """
        now = datetime.now(tz=API_TZ)
        start = now - timedelta(hours=hours_back)
        payload = await self._async_get(
            "meta/json",
            {
                "use": "airquality",
                "lang": "de",
                "date_from": start.date().isoformat(),
                "date_to": now.date().isoformat(),
                "time_from": "1",
                "time_to": "24",
            },
        )
        raw = payload.get("stations")
        if not isinstance(raw, dict) or not raw:
            raise UbaLqiResponseError("Station list missing in meta response")
        stations: dict[str, StationMeta] = {}
        for key, value in raw.items():
            station = _parse_station(key, value)
            if station is not None:
                stations[station.station_id] = station
        if not stations:
            raise UbaLqiResponseError("Station list could not be parsed")
        return stations

    async def async_get_air_quality(
        self, station_id: str, *, hours_back: int
    ) -> StationAirQuality:
        """Return the newest readings per component within the window."""
        now = datetime.now(tz=API_TZ)
        start = now - timedelta(hours=hours_back)
        payload = await self._async_get(
            "airquality/json",
            {
                "station": station_id,
                "lang": "de",
                "date_from": start.date().isoformat(),
                "time_from": "1",
                "date_to": now.date().isoformat(),
                "time_to": "24",
            },
        )
        data = payload.get("data")
        rows = data.get(str(station_id)) if isinstance(data, dict) else None
        if not isinstance(rows, dict):
            rows = {}
        return _parse_station_rows(station_id, rows)


def _parse_station_rows(
    station_id: str, rows: dict[str, Any]
) -> StationAirQuality:
    components: dict[int, ComponentValue] = {}
    newest_start: datetime | None = None
    newest_end: datetime | None = None
    total_index: int | None = None
    all_reported: bool | None = None

    for start_raw, row in rows.items():
        start = _parse_timestamp(start_raw)
        if start is None or not isinstance(row, list) or len(row) < 3:
            continue
        end = _parse_timestamp(row[0]) or (start + timedelta(hours=1))

        for comp_raw in row[3:]:
            if not isinstance(comp_raw, list) or len(comp_raw) < 3:
                continue
            component_id = _as_int(comp_raw[0])
            if component_id is None:
                continue
            existing = components.get(component_id)
            if existing is not None and existing.end >= end:
                continue
            components[component_id] = ComponentValue(
                component_id=component_id,
                value=_as_float(comp_raw[1]),
                index=_as_index(comp_raw[2]),
                threshold_progress=_as_float(comp_raw[3]) if len(comp_raw) > 3 else None,
                start=start,
                end=end,
            )

        if newest_start is None or start > newest_start:
            newest_start = start
            newest_end = end
            # Index 0 ("sehr gut") ist ein gültiger Wert; nur -1/fehlend ist unbekannt.
            total_index = _as_index(row[1])
            incomplete = _as_int(row[2])
            all_reported = None if incomplete is None else incomplete == 0

    return StationAirQuality(
        station_id=str(station_id),
        components=components,
        total_index=total_index,
        newest_start=newest_start,
        newest_end=newest_end,
        all_components_reported=all_reported,
    )


def _parse_station(key: str, raw: Any) -> StationMeta | None:
    if not isinstance(raw, list) or len(raw) < 9:
        return None
    latitude = _as_float(_item(raw, 8))
    longitude = _as_float(_item(raw, 7))
    name = _as_str(_item(raw, 2))
    if name is None:
        return None
    return StationMeta(
        station_id=str(_item(raw, 0) or key),
        code=_as_str(_item(raw, 1)) or "",
        name=name,
        city=_as_str(_item(raw, 3)),
        latitude=latitude,
        longitude=longitude,
        setting=_as_str(_item(raw, 14)),
        station_type=_as_str(_item(raw, 16)),
        street=_as_str(_item(raw, 17)),
        zip_code=_as_str(_item(raw, 19)),
        active_from=_as_str(_item(raw, 5)),
        active_to=_as_str(_item(raw, 6)),
    )


def _parse_timestamp(value: Any) -> datetime | None:
    """Parse an API timestamp (fixed UTC+1, no DST) and return it as UTC."""
    if not isinstance(value, str):
        return None
    try:
        parsed = datetime.strptime(value, _TIME_FORMAT)
    except ValueError:
        return None
    return parsed.replace(tzinfo=API_TZ).astimezone(UTC)


def _item(raw: list[Any], index: int) -> Any:
    return raw[index] if index < len(raw) else None


def _as_float(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _as_int(value: Any) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _as_index(value: Any) -> int | None:
    """Coerce an index class; only 0..4 are valid, -1 means unknown."""
    index = _as_int(value)
    if index is None or not 0 <= index <= 4:
        return None
    return index


def _as_str(value: Any) -> str | None:
    if value is None or value == "":
        return None
    return str(value)
