"""Config flow for the UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

from homeassistant.config_entries import (
    SOURCE_RECONFIGURE,
    ConfigFlow,
    ConfigFlowResult,
    OptionsFlow,
)
from homeassistant.const import CONF_LATITUDE, CONF_LOCATION, CONF_LONGITUDE
from homeassistant.core import callback
from homeassistant.helpers import selector
from homeassistant.helpers.aiohttp_client import async_get_clientsession
import voluptuous as vol

from .api import StationMeta, UbaLqiApiClient, UbaLqiError
from .const import (
    CONF_LOCATION_SOURCE,
    CONF_RADIUS_KM,
    CONF_STATIONS,
    CONF_UPDATE_INTERVAL,
    DEFAULT_RADIUS_KM,
    DEFAULT_UPDATE_INTERVAL_MINUTES,
    DISCOVERY_WINDOW_HOURS,
    DOMAIN,
    LOCATION_SOURCE_HOME,
    LOCATION_SOURCE_MANUAL,
    MAX_CANDIDATE_STATIONS,
    MIN_UPDATE_INTERVAL_MINUTES,
)
from .util import haversine_km


def _user_schema(defaults: dict[str, Any]) -> vol.Schema:
    return vol.Schema(
        {
            vol.Required(
                CONF_LOCATION_SOURCE,
                default=defaults.get(CONF_LOCATION_SOURCE, LOCATION_SOURCE_HOME),
            ): selector.SelectSelector(
                selector.SelectSelectorConfig(
                    options=[LOCATION_SOURCE_HOME, LOCATION_SOURCE_MANUAL],
                    mode=selector.SelectSelectorMode.DROPDOWN,
                    translation_key="location_source",
                )
            ),
            vol.Required(
                CONF_RADIUS_KM,
                default=defaults.get(CONF_RADIUS_KM, DEFAULT_RADIUS_KM),
            ): selector.NumberSelector(
                selector.NumberSelectorConfig(
                    min=5,
                    max=200,
                    step=5,
                    mode=selector.NumberSelectorMode.SLIDER,
                    unit_of_measurement="km",
                )
            ),
        }
    )


class UbaLqiConfigFlow(ConfigFlow, domain=DOMAIN):
    """Handle the configuration of stations by location."""

    VERSION = 2
    MINOR_VERSION = 0

    def __init__(self) -> None:
        self._data: dict[str, Any] = {}
        self._candidates: list[tuple[StationMeta, float]] = []

    @property
    def _client(self) -> UbaLqiApiClient:
        return UbaLqiApiClient(async_get_clientsession(self.hass))

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """First step: location source and search radius."""
        errors: dict[str, str] = {}
        if user_input is not None:
            self._data[CONF_LOCATION_SOURCE] = user_input[CONF_LOCATION_SOURCE]
            self._data[CONF_RADIUS_KM] = int(user_input[CONF_RADIUS_KM])
            if user_input[CONF_LOCATION_SOURCE] == LOCATION_SOURCE_MANUAL:
                return await self.async_step_manual_location()
            self._data[CONF_LATITUDE] = float(self.hass.config.latitude)
            self._data[CONF_LONGITUDE] = float(self.hass.config.longitude)
            return await self._async_load_candidates()
        return self.async_show_form(
            step_id="user", data_schema=_user_schema(self._data), errors=errors
        )

    async def async_step_reconfigure(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Allow changing location, radius and stations without re-adding."""
        entry = self._get_reconfigure_entry()
        self._data = {
            CONF_LOCATION_SOURCE: entry.data.get(
                CONF_LOCATION_SOURCE, LOCATION_SOURCE_HOME
            ),
            CONF_RADIUS_KM: entry.data.get(CONF_RADIUS_KM, DEFAULT_RADIUS_KM),
            CONF_LATITUDE: entry.data.get(CONF_LATITUDE),
            CONF_LONGITUDE: entry.data.get(CONF_LONGITUDE),
        }
        return await self.async_step_user()

    async def async_step_manual_location(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Pick coordinates on a map."""
        if user_input is not None:
            location = user_input[CONF_LOCATION]
            self._data[CONF_LATITUDE] = float(location[CONF_LATITUDE])
            self._data[CONF_LONGITUDE] = float(location[CONF_LONGITUDE])
            return await self._async_load_candidates()
        default_location = {
            CONF_LATITUDE: self._data.get(CONF_LATITUDE)
            or self.hass.config.latitude,
            CONF_LONGITUDE: self._data.get(CONF_LONGITUDE)
            or self.hass.config.longitude,
        }
        return self.async_show_form(
            step_id="manual_location",
            data_schema=vol.Schema(
                {
                    vol.Required(
                        CONF_LOCATION, default=default_location
                    ): selector.LocationSelector()
                }
            ),
        )

    async def _async_load_candidates(self) -> ConfigFlowResult:
        """Fetch the active station list and rank it by distance."""
        try:
            stations = await self._client.async_get_stations()
        except UbaLqiError:
            return self.async_show_form(
                step_id="user",
                data_schema=_user_schema(self._data),
                errors={"base": "cannot_connect"},
            )
        latitude = self._data[CONF_LATITUDE]
        longitude = self._data[CONF_LONGITUDE]
        ranked = sorted(
            (
                (station, haversine_km(latitude, longitude, station.latitude, station.longitude))
                for station in stations.values()
                if station.latitude is not None and station.longitude is not None
            ),
            key=lambda item: item[1],
        )
        radius = float(self._data[CONF_RADIUS_KM])
        self._candidates = [
            (station, distance) for station, distance in ranked if distance <= radius
        ][:MAX_CANDIDATE_STATIONS]
        if not self._candidates:
            return self.async_show_form(
                step_id="user",
                data_schema=_user_schema(self._data),
                errors={"base": "no_stations_found"},
            )
        return await self.async_step_select_stations()

    async def async_step_select_stations(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Let the user pick one or more stations."""
        errors: dict[str, str] = {}
        if user_input is not None:
            selected = [str(station_id) for station_id in user_input[CONF_STATIONS]]
            if not selected:
                errors[CONF_STATIONS] = "no_station_selected"
            elif self._configured_elsewhere(selected):
                errors[CONF_STATIONS] = "station_already_configured"
            else:
                try:
                    return await self._async_finish(selected)
                except UbaLqiError:
                    errors["base"] = "cannot_connect"

        by_distance = {station.station_id: distance for station, distance in self._candidates}
        options = [
            selector.SelectOptionDict(
                value=station.station_id,
                label=_station_label(station, distance),
            )
            for station, distance in self._candidates
        ]
        current = [
            station_id
            for station_id in self._existing_selection()
            if station_id in by_distance
        ] or [self._candidates[0][0].station_id]
        return self.async_show_form(
            step_id="select_stations",
            data_schema=vol.Schema(
                {
                    vol.Required(
                        CONF_STATIONS, default=current
                    ): selector.SelectSelector(
                        selector.SelectSelectorConfig(
                            options=options,
                            multiple=True,
                            mode=selector.SelectSelectorMode.LIST,
                        )
                    )
                }
            ),
            errors=errors,
            description_placeholders={
                "count": str(len(self._candidates)),
                "radius": str(self._data[CONF_RADIUS_KM]),
            },
        )

    async def _async_finish(self, selected: list[str]) -> ConfigFlowResult:
        """Determine measured components per station and create the entry.

        Die Komponentenlisten werden hier einmalig über ein 48-h-Fenster
        ermittelt und im Eintrag gespeichert; Entitäten entstehen später aus
        diesen Metadaten statt aus der ersten API-Antwort.
        """
        client = self._client
        stations: dict[str, dict[str, Any]] = {}
        selected_ranked = [
            (station, distance)
            for station, distance in self._candidates
            if station.station_id in selected
        ]
        for station, distance in selected_ranked:
            air = await client.async_get_air_quality(
                station.station_id, hours_back=DISCOVERY_WINDOW_HOURS
            )
            stations[station.station_id] = {
                "code": station.code,
                "name": station.name,
                "city": station.city,
                "latitude": station.latitude,
                "longitude": station.longitude,
                "setting": station.setting,
                "station_type": station.station_type,
                "distance_km": round(distance, 2),
                "components": sorted(air.components),
            }

        data = {
            CONF_LOCATION_SOURCE: self._data[CONF_LOCATION_SOURCE],
            CONF_LATITUDE: self._data[CONF_LATITUDE],
            CONF_LONGITUDE: self._data[CONF_LONGITUDE],
            CONF_RADIUS_KM: self._data[CONF_RADIUS_KM],
            CONF_STATIONS: stations,
        }
        names = [config["name"] for config in stations.values()]
        title = ", ".join(names[:2]) + (f" +{len(names) - 2}" if len(names) > 2 else "")

        if self.source == SOURCE_RECONFIGURE:
            return self.async_update_reload_and_abort(
                self._get_reconfigure_entry(), data=data, title=title
            )
        return self.async_create_entry(title=title, data=data)

    def _configured_elsewhere(self, selected: list[str]) -> set[str]:
        """Stations already used by another entry (device IDs must stay unique)."""
        current_entry_id = (
            self._get_reconfigure_entry().entry_id
            if self.source == SOURCE_RECONFIGURE
            else None
        )
        existing: set[str] = set()
        for entry in self._async_current_entries(include_ignore=False):
            if entry.entry_id == current_entry_id:
                continue
            existing.update(entry.data.get(CONF_STATIONS, {}))
        return existing & set(selected)

    def _existing_selection(self) -> list[str]:
        if self.source == SOURCE_RECONFIGURE:
            return list(self._get_reconfigure_entry().data.get(CONF_STATIONS, {}))
        return []

    @staticmethod
    @callback
    def async_get_options_flow(config_entry: Any) -> UbaLqiOptionsFlow:
        """Return the options flow."""
        return UbaLqiOptionsFlow()


class UbaLqiOptionsFlow(OptionsFlow):
    """Runtime options: polling interval."""

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        if user_input is not None:
            return self.async_create_entry(
                data={CONF_UPDATE_INTERVAL: int(user_input[CONF_UPDATE_INTERVAL])}
            )
        return self.async_show_form(
            step_id="init",
            data_schema=vol.Schema(
                {
                    vol.Required(
                        CONF_UPDATE_INTERVAL,
                        default=self.config_entry.options.get(
                            CONF_UPDATE_INTERVAL, DEFAULT_UPDATE_INTERVAL_MINUTES
                        ),
                    ): selector.NumberSelector(
                        selector.NumberSelectorConfig(
                            min=MIN_UPDATE_INTERVAL_MINUTES,
                            max=360,
                            step=5,
                            mode=selector.NumberSelectorMode.BOX,
                            unit_of_measurement="min",
                        )
                    )
                }
            ),
        )


def _station_label(station: StationMeta, distance: float) -> str:
    """Human-readable candidate label including measurement profile."""
    parts = [station.name]
    if station.city and station.city not in station.name:
        parts[0] = f"{station.name} ({station.city})"
    parts.append(f"{distance:.1f} km")
    profile = " / ".join(
        part for part in (station.station_type, station.setting) if part
    )
    if profile:
        parts.append(profile)
    return " · ".join(parts)
