"""Constants for the UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from datetime import timedelta, timezone
from typing import Final

DOMAIN: Final = "uba_lqi"

# Die v4-API ist die einzige aktuell gepflegte Generation. v2/v3 liefern
# einen Altbestand ohne PM2,5 und rechnen mit veralteten Index-Schwellen.
API_BASE_URL: Final = "https://luftdaten.umweltbundesamt.de/api/air-data/v4"
API_TIMEOUT: Final = 30

# Die API liefert alle Zeitstempel ganzjährig in MEZ (UTC+1, keine Sommerzeit).
API_TZ: Final = timezone(timedelta(hours=1), name="UTC+01:00")

ATTRIBUTION: Final = "Daten: Umweltbundesamt, luftdaten.umweltbundesamt.de"

CONF_LOCATION_SOURCE: Final = "location_source"
CONF_RADIUS_KM: Final = "radius_km"
CONF_STATIONS: Final = "stations"
CONF_UPDATE_INTERVAL: Final = "update_interval_minutes"

LOCATION_SOURCE_HOME: Final = "home"
LOCATION_SOURCE_MANUAL: Final = "manual"

DEFAULT_RADIUS_KM: Final = 50
DEFAULT_UPDATE_INTERVAL_MINUTES: Final = 60
MIN_UPDATE_INTERVAL_MINUTES: Final = 15
MAX_CANDIDATE_STATIONS: Final = 25

# Abfragefenster je Aktualisierung: pro Komponente wird der jüngste Wert im
# Fenster verwendet, damit einzelne "hinkende" Komponenten nicht verloren gehen.
FETCH_WINDOW_HOURS: Final = 24
# Rückblick-Fenster für Stationsliste und Komponenten im Config Flow sowie für
# die einmalige Suche nach der letzten Messung nach dem Start. Großzügig
# gewählt, damit beides auch während eines mehrtägigen Datenausfalls beim UBA
# funktioniert; die Stationsliste wächst dadurch nicht (weiterhin ~420).
DISCOVERY_WINDOW_HOURS: Final = 14 * 24
# Werte, deren Messintervall länger zurückliegt, gelten als veraltet.
STALE_AFTER: Final = timedelta(hours=3)
# Station so lange ohne jegliche Daten -> Repair Issue.
SILENT_AFTER: Final = timedelta(hours=24)
# Exponentielles Backoff im Fehlerfall, gedeckelt.
BACKOFF_MAX: Final = timedelta(hours=6)

# Reihenfolge entspricht den Index-Klassen 0..4 der API.
LQI_OPTIONS: Final[list[str]] = [
    "very_good",
    "good",
    "moderate",
    "poor",
    "very_poor",
]

ISSUE_STATION_SILENT: Final = "station_silent"
