"""Data update coordinator for the UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import asyncio
from collections.abc import Iterable
from dataclasses import dataclass, field
from datetime import datetime, timedelta
import logging
from typing import TYPE_CHECKING, Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers import issue_registry as ir
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed
from homeassistant.util import dt as dt_util

from .api import (
    ComponentValue,
    StationAirQuality,
    UbaLqiApiClient,
    UbaLqiError,
)
from .const import (
    BACKOFF_MAX,
    CONF_STATIONS,
    CONF_UPDATE_INTERVAL,
    DEFAULT_UPDATE_INTERVAL_MINUTES,
    DOMAIN,
    FETCH_WINDOW_HOURS,
    ISSUE_STATION_SILENT,
    SILENT_AFTER,
    STALE_AFTER,
)

if TYPE_CHECKING:
    from . import UbaLqiConfigEntry

_LOGGER = logging.getLogger(__name__)


@dataclass(slots=True)
class StationState:
    """Processed state of a single station."""

    station_id: str
    config: dict[str, Any]
    air: StationAirQuality | None
    fresh: dict[int, ComponentValue] = field(default_factory=dict)
    lqi: int | None = None
    driver_component: int | None = None
    last_measurement: datetime | None = None


@dataclass(slots=True)
class AggregateState:
    """Worst-case air quality across all configured stations."""

    lqi: int | None = None
    driver_station: str | None = None
    driver_component: int | None = None
    # Je Komponente der Wert der nächstgelegenen Station, die sie frisch liefert.
    components: dict[int, tuple[str, ComponentValue]] = field(default_factory=dict)
    last_measurement: datetime | None = None


@dataclass(slots=True)
class UbaLqiData:
    """Data held by the coordinator."""

    stations: dict[str, StationState]
    aggregate: AggregateState


class UbaLqiCoordinator(DataUpdateCoordinator[UbaLqiData]):
    """Poll the UBA API once per interval and derive fresh values."""

    config_entry: UbaLqiConfigEntry

    def __init__(
        self,
        hass: HomeAssistant,
        entry: UbaLqiConfigEntry,
        client: UbaLqiApiClient,
    ) -> None:
        self.client = client
        self._base_interval = timedelta(
            minutes=int(
                entry.options.get(CONF_UPDATE_INTERVAL, DEFAULT_UPDATE_INTERVAL_MINUTES)
            )
        )
        self._consecutive_failures = 0
        self._stations_without_data: set[str] = set()
        super().__init__(
            hass,
            _LOGGER,
            config_entry=entry,
            name=f"{DOMAIN} ({entry.title})",
            update_interval=self._base_interval,
        )

    async def _async_update_data(self) -> UbaLqiData:
        stations_config: dict[str, dict[str, Any]] = self.config_entry.data[
            CONF_STATIONS
        ]
        results = await asyncio.gather(
            *(
                self.client.async_get_air_quality(
                    station_id, hours_back=FETCH_WINDOW_HOURS
                )
                for station_id in stations_config
            ),
            return_exceptions=True,
        )

        errors: dict[str, Exception] = {}
        readings: dict[str, StationAirQuality] = {}
        for station_id, result in zip(stations_config, results, strict=True):
            if isinstance(result, StationAirQuality):
                readings[station_id] = result
            elif isinstance(result, UbaLqiError):
                errors[station_id] = result
            elif isinstance(result, BaseException):
                raise result

        if not readings:
            self._consecutive_failures += 1
            self._apply_backoff()
            raise UpdateFailed(
                translation_domain=DOMAIN,
                translation_key="update_failed",
                translation_placeholders={
                    "error": str(next(iter(errors.values()), "no data"))
                },
            )

        # Erfolg (auch teilweise): Backoff zurücksetzen.
        self._consecutive_failures = 0
        if self.update_interval != self._base_interval:
            _LOGGER.info(
                "UBA API reachable again, restoring update interval of %s",
                self._base_interval,
            )
            self.update_interval = self._base_interval

        for station_id, error in errors.items():
            _LOGGER.warning(
                "Fetching air quality for station %s failed, keeping it unavailable: %s",
                station_id,
                error,
            )

        now = dt_util.utcnow()
        cutoff = now - STALE_AFTER
        previous = self.data.stations if self.data else {}
        stations: dict[str, StationState] = {}
        for station_id, config in stations_config.items():
            air = readings.get(station_id)
            if air is None and station_id in previous:
                # Transienter Fehler einer einzelnen Station: den letzten
                # bekannten Rohstand behalten - die Frische-Grenze altert die
                # Werte von selbst aus, "Letzte Messung" bleibt sichtbar.
                air = previous[station_id].air
            stations[station_id] = self._build_station_state(
                station_id, config, air, cutoff
            )

        self._report_data_gaps(stations, now)
        return UbaLqiData(
            stations=stations, aggregate=_build_aggregate(stations.values())
        )

    def _build_station_state(
        self,
        station_id: str,
        config: dict[str, Any],
        air: StationAirQuality | None,
        cutoff: datetime,
    ) -> StationState:
        state = StationState(station_id=station_id, config=config, air=air)
        if air is None:
            return state
        state.last_measurement = air.newest_end
        state.fresh = {
            component_id: value
            for component_id, value in air.components.items()
            if value.end >= cutoff
        }
        indexed = {
            component_id: value.index
            for component_id, value in state.fresh.items()
            if value.index is not None
        }
        if indexed:
            # Offizielle Definition: der schlechteste Einzelindex.
            state.driver_component = max(indexed, key=lambda cid: indexed[cid])
            state.lqi = indexed[state.driver_component]
        return state

    def _report_data_gaps(
        self, stations: dict[str, StationState], now: datetime
    ) -> None:
        """Sichtbarkeit des Versagens: loggen und Repair Issues pflegen."""
        for station_id, state in stations.items():
            name = state.config.get("name", station_id)
            has_fresh = bool(state.fresh)
            if not has_fresh and station_id not in self._stations_without_data:
                self._stations_without_data.add(station_id)
                _LOGGER.warning(
                    "Station %s (%s) has no fresh data (newest measurement: %s)",
                    name,
                    station_id,
                    state.last_measurement.isoformat()
                    if state.last_measurement
                    else "none",
                )
            elif has_fresh and station_id in self._stations_without_data:
                self._stations_without_data.discard(station_id)
                _LOGGER.info(
                    "Station %s (%s) is delivering data again", name, station_id
                )

            issue_id = f"{ISSUE_STATION_SILENT}_{station_id}"
            silent = state.last_measurement is None or (
                now - state.last_measurement > SILENT_AFTER
            )
            if silent and state.air is not None:
                ir.async_create_issue(
                    self.hass,
                    DOMAIN,
                    issue_id,
                    is_fixable=False,
                    is_persistent=False,
                    severity=ir.IssueSeverity.WARNING,
                    translation_key=ISSUE_STATION_SILENT,
                    translation_placeholders={
                        "station": str(name),
                        "last": state.last_measurement.isoformat()
                        if state.last_measurement
                        else "-",
                    },
                    learn_more_url="https://www.umweltbundesamt.de/daten/luft/luftdaten",
                )
            elif not silent:
                ir.async_delete_issue(self.hass, DOMAIN, issue_id)

    def _apply_backoff(self) -> None:
        interval = min(
            self._base_interval * (2 ** min(self._consecutive_failures, 5)),
            BACKOFF_MAX,
        )
        if interval != self.update_interval:
            _LOGGER.warning(
                "UBA API failed %d time(s) in a row, raising update interval to %s",
                self._consecutive_failures,
                interval,
            )
            self.update_interval = interval


def _build_aggregate(stations: Iterable[StationState]) -> AggregateState:
    aggregate = AggregateState()
    for state in stations:
        for component_id, value in state.fresh.items():
            # Je Komponente gewinnt die nähere Station; Stationen sind in der
            # Konfiguration bereits nach Entfernung sortiert abgelegt.
            if value.index is None or component_id in aggregate.components:
                continue
            aggregate.components[component_id] = (state.station_id, value)
            if aggregate.lqi is None or value.index > aggregate.lqi:
                aggregate.lqi = value.index
                aggregate.driver_station = state.station_id
                aggregate.driver_component = component_id
        if state.last_measurement is not None and (
            aggregate.last_measurement is None
            or state.last_measurement > aggregate.last_measurement
        ):
            aggregate.last_measurement = state.last_measurement
    return aggregate
