"""Diagnostics support for the UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

from homeassistant.components.diagnostics import async_redact_data
from homeassistant.core import HomeAssistant

from . import UbaLqiConfigEntry
from .coordinator import StationState

# Die Heimkoordinaten des Nutzers werden geschwärzt; Stationskoordinaten
# sind öffentliche Infrastrukturdaten und bleiben sichtbar.
TO_REDACT = {"latitude", "longitude"}


async def async_get_config_entry_diagnostics(
    hass: HomeAssistant, entry: UbaLqiConfigEntry
) -> dict[str, Any]:
    """Return diagnostics for a config entry."""
    coordinator = entry.runtime_data
    return {
        "entry": {
            "data": async_redact_data(dict(entry.data), TO_REDACT),
            "options": dict(entry.options),
        },
        "update": {
            "last_update_success": coordinator.last_update_success,
            "update_interval": str(coordinator.update_interval),
        },
        "stations": {
            station_id: _station_diagnostics(state)
            for station_id, state in coordinator.data.stations.items()
        },
        "aggregate": {
            "lqi": coordinator.data.aggregate.lqi,
            "driver_station": coordinator.data.aggregate.driver_station,
            "driver_component": coordinator.data.aggregate.driver_component,
        },
    }


def _station_diagnostics(state: StationState) -> dict[str, Any]:
    return {
        "lqi": state.lqi,
        "driver_component": state.driver_component,
        "last_measurement": (
            state.last_measurement.isoformat() if state.last_measurement else None
        ),
        "fresh_components": {
            component_id: {
                "value": value.value,
                "index": value.index,
                "measured_until": value.end.isoformat(),
            }
            for component_id, value in state.fresh.items()
        },
        "raw_component_count": (
            len(state.air.components) if state.air is not None else None
        ),
        "all_components_reported": (
            state.air.all_components_reported if state.air is not None else None
        ),
    }
