"""Base entities for the UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import ATTRIBUTION, DOMAIN
from .coordinator import UbaLqiCoordinator

MANUFACTURER = "Umweltbundesamt"


class UbaLqiStationEntity(CoordinatorEntity[UbaLqiCoordinator]):
    """Entity attached to a single measuring station device."""

    _attr_attribution = ATTRIBUTION
    _attr_has_entity_name = True

    def __init__(
        self,
        coordinator: UbaLqiCoordinator,
        station_id: str,
        station_config: dict[str, Any],
    ) -> None:
        super().__init__(coordinator)
        self._station_id = station_id
        self._station_config = station_config
        model_parts = [
            part
            for part in (
                station_config.get("station_type"),
                station_config.get("setting"),
            )
            if part
        ]
        name = station_config.get("name") or station_id
        city = station_config.get("city")
        if city and city not in name:
            name = f"{name} ({city})"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, station_id)},
            name=name,
            manufacturer=MANUFACTURER,
            model=" · ".join(model_parts) or "Luftmessstation",
            serial_number=station_config.get("code"),
            configuration_url="https://luftdaten.umweltbundesamt.de",
        )


class UbaLqiCombinedEntity(CoordinatorEntity[UbaLqiCoordinator]):
    """Entity attached to the combined (worst-case) service device."""

    _attr_attribution = ATTRIBUTION
    _attr_has_entity_name = True

    def __init__(self, coordinator: UbaLqiCoordinator) -> None:
        super().__init__(coordinator)
        entry_id = coordinator.config_entry.entry_id
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, f"{entry_id}_combined")},
            name="Luftqualität kombiniert",
            manufacturer=MANUFACTURER,
            model="Schlechtester Einzelindex aller Stationen",
            entry_type=DeviceEntryType.SERVICE,
            configuration_url="https://luftdaten.umweltbundesamt.de",
        )
