"""Sensor platform for the UBA Luftqualitätsindex (LQI) integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from typing import Any

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
    CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER,
    EntityCategory,
    UnitOfLength,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.typing import StateType

from . import UbaLqiConfigEntry
from .const import CONF_STATIONS, LQI_OPTIONS
from .coordinator import StationState, UbaLqiCoordinator
from .entity import UbaLqiCombinedEntity, UbaLqiStationEntity

# Der Coordinator bündelt alle Netzwerkzugriffe.
PARALLEL_UPDATES = 0

_NANOGRAMS_PER_CUBIC_METER = "ng/m³"


@dataclass(frozen=True, kw_only=True)
class UbaLqiSensorEntityDescription(SensorEntityDescription):
    """Describes a station-level UBA LQI sensor."""

    value_fn: Callable[[StationState], StateType | datetime]
    available_fn: Callable[[StationState], bool] = lambda state: True
    attributes_fn: Callable[[StationState], dict[str, Any] | None] | None = None


STATION_SENSORS: tuple[UbaLqiSensorEntityDescription, ...] = (
    UbaLqiSensorEntityDescription(
        key="lqi",
        translation_key="lqi",
        device_class=SensorDeviceClass.ENUM,
        options=LQI_OPTIONS,
        value_fn=lambda state: None if state.lqi is None else LQI_OPTIONS[state.lqi],
        available_fn=lambda state: state.lqi is not None,
        attributes_fn=lambda state: _station_attributes(state),
    ),
    UbaLqiSensorEntityDescription(
        key="lqi_numeric",
        translation_key="lqi_numeric",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=lambda state: state.lqi,
        available_fn=lambda state: state.lqi is not None,
    ),
    UbaLqiSensorEntityDescription(
        key="last_measurement",
        translation_key="last_measurement",
        device_class=SensorDeviceClass.TIMESTAMP,
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda state: state.last_measurement,
        available_fn=lambda state: state.last_measurement is not None,
    ),
    UbaLqiSensorEntityDescription(
        key="distance",
        translation_key="distance",
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        suggested_display_precision=1,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        value_fn=lambda state: state.config.get("distance_km"),
        available_fn=lambda state: state.config.get("distance_km") is not None,
    ),
)


@dataclass(frozen=True, kw_only=True)
class UbaLqiComponentDescription:
    """Static description of an API pollutant component."""

    translation_key: str
    unit: str
    device_class: SensorDeviceClass | None = None
    enabled_default: bool = True


# Kennungen laut components/json der v4-API.
COMPONENT_DESCRIPTIONS: dict[int, UbaLqiComponentDescription] = {
    1: UbaLqiComponentDescription(
        translation_key="pm10",
        unit=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        device_class=SensorDeviceClass.PM10,
    ),
    2: UbaLqiComponentDescription(
        translation_key="co",
        # Die API liefert CO in mg/m³; HA erlaubt diese Einheit für die
        # CO-Geräteklasse seit langem nativ - keine Umrechnung nötig.
        unit=CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER,
        device_class=SensorDeviceClass.CO,
    ),
    3: UbaLqiComponentDescription(
        translation_key="o3",
        unit=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        device_class=SensorDeviceClass.OZONE,
    ),
    4: UbaLqiComponentDescription(
        translation_key="so2",
        unit=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        device_class=SensorDeviceClass.SULPHUR_DIOXIDE,
    ),
    5: UbaLqiComponentDescription(
        translation_key="no2",
        unit=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        device_class=SensorDeviceClass.NITROGEN_DIOXIDE,
    ),
    6: UbaLqiComponentDescription(
        translation_key="lead",
        unit=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        enabled_default=False,
    ),
    7: UbaLqiComponentDescription(
        translation_key="benzo_a_pyrene",
        unit=_NANOGRAMS_PER_CUBIC_METER,
        enabled_default=False,
    ),
    8: UbaLqiComponentDescription(
        translation_key="benzene",
        unit=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        enabled_default=False,
    ),
    9: UbaLqiComponentDescription(
        translation_key="pm25",
        unit=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        device_class=SensorDeviceClass.PM25,
    ),
    10: UbaLqiComponentDescription(
        translation_key="arsenic",
        unit=_NANOGRAMS_PER_CUBIC_METER,
        enabled_default=False,
    ),
    11: UbaLqiComponentDescription(
        translation_key="cadmium",
        unit=_NANOGRAMS_PER_CUBIC_METER,
        enabled_default=False,
    ),
    12: UbaLqiComponentDescription(
        translation_key="nickel",
        unit=_NANOGRAMS_PER_CUBIC_METER,
        enabled_default=False,
    ),
}

COMBINED_SENSORS: tuple[SensorEntityDescription, ...] = (
    SensorEntityDescription(
        key="combined_lqi",
        translation_key="combined_lqi",
        device_class=SensorDeviceClass.ENUM,
        options=LQI_OPTIONS,
    ),
    SensorEntityDescription(
        key="combined_lqi_numeric",
        translation_key="combined_lqi_numeric",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        state_class=SensorStateClass.MEASUREMENT,
    ),
)


def expected_unique_ids(entry: UbaLqiConfigEntry) -> set[str]:
    """Unique IDs of all entities this entry is supposed to have."""
    unique_ids: set[str] = set()
    for station_id, config in entry.data[CONF_STATIONS].items():
        unique_ids.update(
            f"{station_id}_{description.key}" for description in STATION_SENSORS
        )
        for component_id in config.get("components") or []:
            unique_ids.add(f"{station_id}_component_{component_id}")
    unique_ids.update(
        f"{entry.entry_id}_{description.key}" for description in COMBINED_SENSORS
    )
    return unique_ids


async def async_setup_entry(
    hass: HomeAssistant,
    entry: UbaLqiConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up sensors from the stored station metadata."""
    coordinator = entry.runtime_data
    entities: list[SensorEntity] = []

    for station_id, config in entry.data[CONF_STATIONS].items():
        entities.extend(
            UbaLqiStationSensor(coordinator, station_id, config, description)
            for description in STATION_SENSORS
        )
        entities.extend(
            UbaLqiComponentSensor(coordinator, station_id, config, component_id)
            for component_id in config.get("components") or []
            if component_id in COMPONENT_DESCRIPTIONS
        )

    entities.extend(
        UbaLqiCombinedSensor(coordinator, description)
        for description in COMBINED_SENSORS
    )
    async_add_entities(entities)


class UbaLqiStationSensor(UbaLqiStationEntity, SensorEntity):
    """Station-level sensor driven by an entity description."""

    entity_description: UbaLqiSensorEntityDescription

    def __init__(
        self,
        coordinator: UbaLqiCoordinator,
        station_id: str,
        station_config: dict[str, Any],
        description: UbaLqiSensorEntityDescription,
    ) -> None:
        super().__init__(coordinator, station_id, station_config)
        self.entity_description = description
        self._attr_unique_id = f"{station_id}_{description.key}"

    @property
    def _station_state(self) -> StationState | None:
        return self.coordinator.data.stations.get(self._station_id)

    @property
    def available(self) -> bool:
        state = self._station_state
        return (
            super().available
            and state is not None
            and self.entity_description.available_fn(state)
        )

    @property
    def native_value(self) -> StateType | datetime:
        state = self._station_state
        if state is None:
            return None
        return self.entity_description.value_fn(state)

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        if self.entity_description.attributes_fn is None:
            return None
        state = self._station_state
        if state is None:
            return None
        return self.entity_description.attributes_fn(state)


class UbaLqiComponentSensor(UbaLqiStationEntity, SensorEntity):
    """Measured concentration of one pollutant at one station."""

    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_suggested_display_precision = 1

    def __init__(
        self,
        coordinator: UbaLqiCoordinator,
        station_id: str,
        station_config: dict[str, Any],
        component_id: int,
    ) -> None:
        super().__init__(coordinator, station_id, station_config)
        self._component_id = component_id
        description = COMPONENT_DESCRIPTIONS[component_id]
        self._attr_unique_id = f"{station_id}_component_{component_id}"
        self._attr_translation_key = description.translation_key
        self._attr_native_unit_of_measurement = description.unit
        self._attr_device_class = description.device_class
        self._attr_entity_registry_enabled_default = description.enabled_default

    @property
    def _component_value(self) -> Any:
        state = self.coordinator.data.stations.get(self._station_id)
        if state is None:
            return None
        return state.fresh.get(self._component_id)

    @property
    def available(self) -> bool:
        value = self._component_value
        return super().available and value is not None and value.value is not None

    @property
    def native_value(self) -> float | None:
        value = self._component_value
        return None if value is None else value.value

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        value = self._component_value
        if value is None:
            return None
        return {
            "index": value.index,
            "level": None if value.index is None else LQI_OPTIONS[value.index],
            "threshold_progress": value.threshold_progress,
            "measured_from": value.start.isoformat(),
            "measured_until": value.end.isoformat(),
        }


class UbaLqiCombinedSensor(UbaLqiCombinedEntity, SensorEntity):
    """Worst single index across all configured stations."""

    def __init__(
        self, coordinator: UbaLqiCoordinator, description: SensorEntityDescription
    ) -> None:
        super().__init__(coordinator)
        self.entity_description = description
        self._attr_unique_id = f"{coordinator.config_entry.entry_id}_{description.key}"

    @property
    def available(self) -> bool:
        return super().available and self.coordinator.data.aggregate.lqi is not None

    @property
    def native_value(self) -> StateType:
        lqi = self.coordinator.data.aggregate.lqi
        if lqi is None:
            return None
        if self.entity_description.device_class == SensorDeviceClass.ENUM:
            return LQI_OPTIONS[lqi]
        return lqi

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        if self.entity_description.device_class != SensorDeviceClass.ENUM:
            return None
        aggregate = self.coordinator.data.aggregate
        stations = self.coordinator.data.stations
        components: dict[str, Any] = {}
        for component_id, (station_id, value) in sorted(aggregate.components.items()):
            description = COMPONENT_DESCRIPTIONS.get(component_id)
            key = description.translation_key if description else str(component_id)
            station = stations.get(station_id)
            components[key] = {
                "value": value.value,
                "unit": description.unit if description else None,
                "index": value.index,
                "station": station.config.get("name") if station else station_id,
                "measured_until": value.end.isoformat(),
            }
        driver = COMPONENT_DESCRIPTIONS.get(aggregate.driver_component or -1)
        driver_station = stations.get(aggregate.driver_station or "")
        return {
            "lqi": aggregate.lqi,
            "worst_component": driver.translation_key if driver else None,
            "worst_component_station": (
                driver_station.config.get("name") if driver_station else None
            ),
            "stations": [
                state.config.get("name") or station_id
                for station_id, state in stations.items()
            ],
            "last_measurement": (
                aggregate.last_measurement.isoformat()
                if aggregate.last_measurement
                else None
            ),
            "components": components,
        }


def _station_attributes(state: StationState) -> dict[str, Any]:
    components: dict[str, Any] = {}
    for component_id, value in sorted(state.fresh.items()):
        description = COMPONENT_DESCRIPTIONS.get(component_id)
        key = description.translation_key if description else str(component_id)
        components[key] = {
            "value": value.value,
            "unit": description.unit if description else None,
            "index": value.index,
            "measured_until": value.end.isoformat(),
        }
    driver = COMPONENT_DESCRIPTIONS.get(state.driver_component or -1)
    air = state.air
    return {
        "station_id": state.station_id,
        "station_code": state.config.get("code"),
        "city": state.config.get("city"),
        "setting": state.config.get("setting"),
        "station_type": state.config.get("station_type"),
        "distance_km": state.config.get("distance_km"),
        "lqi": state.lqi,
        "worst_component": driver.translation_key if driver else None,
        "all_components_reported": (
            air.all_components_reported if air is not None else None
        ),
        "measured_from": (
            air.newest_start.isoformat() if air and air.newest_start else None
        ),
        "measured_until": (
            air.newest_end.isoformat() if air and air.newest_end else None
        ),
        "components": components,
    }
