"""Shared fixtures for the UBA LQI tests.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from unittest.mock import patch

import pytest
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.uba_lqi.api import (
    ComponentValue,
    StationAirQuality,
    StationMeta,
    UbaLqiApiClient,
)
from custom_components.uba_lqi.const import DOMAIN, FETCH_WINDOW_HOURS

# Eingefrorene Testzeit: 07:30 MEZ = 06:30 UTC.
NOW_UTC = datetime(2026, 8, 7, 6, 30, tzinfo=UTC)
FRESH_END = datetime(2026, 8, 7, 6, 0, tzinfo=UTC)
LAGGING_END = datetime(2026, 8, 7, 5, 0, tzinfo=UTC)
STALE_END = datetime(2026, 8, 7, 2, 0, tzinfo=UTC)

HOME_LAT = 50.73
HOME_LON = 7.09


def station_meta(
    station_id: str,
    name: str,
    latitude: float,
    longitude: float,
    city: str | None = None,
) -> StationMeta:
    return StationMeta(
        station_id=station_id,
        code=f"DE{station_id}",
        name=name,
        city=city,
        latitude=latitude,
        longitude=longitude,
        setting="vorstädtisches Gebiet",
        station_type="Hintergrund",
        street=None,
        zip_code=None,
        active_from="1986-12-01",
        active_to=None,
    )


DEFAULT_STATIONS = {
    "1117": station_meta("1117", "Bonn-Auerberg", 50.7536, 7.0826, "Bonn"),
    "1114": station_meta("1114", "Köln-Rodenkirchen", 50.8942, 6.9910, "Köln"),
    "633": station_meta("633", "Karlsruhe-Nordwest", 49.0243, 8.3625, "Karlsruhe"),
}


def component(
    component_id: int,
    value: float,
    index: int | None,
    end: datetime = FRESH_END,
) -> ComponentValue:
    return ComponentValue(
        component_id=component_id,
        value=value,
        index=index,
        threshold_progress=None,
        start=end - timedelta(hours=1),
        end=end,
    )


def air(
    station_id: str,
    components: list[ComponentValue],
    all_reported: bool = True,
) -> StationAirQuality:
    newest_end = max((c.end for c in components), default=None)
    newest_start = None if newest_end is None else newest_end - timedelta(hours=1)
    indices = [c.index for c in components if c.index is not None]
    return StationAirQuality(
        station_id=station_id,
        components={c.component_id: c for c in components},
        total_index=max(indices) if indices else None,
        newest_start=newest_start,
        newest_end=newest_end,
        all_components_reported=all_reported,
    )


def bonn_air() -> StationAirQuality:
    """Bonn-Auerberg: PM10/PM2,5/NO2, alles „gut", kein Ozon."""
    return air(
        "1117",
        [
            component(1, 20.0, 1),
            component(5, 15.0, 1, end=LAGGING_END),
            component(9, 11.0, 1),
        ],
    )


def koeln_air() -> StationAirQuality:
    """Köln-Rodenkirchen: alle fünf Indexkomponenten, O3 „mäßig"."""
    return air(
        "1114",
        [
            component(1, 18.0, 1),
            component(3, 106.0, 2),
            component(4, 2.0, 0),
            component(5, 9.0, 0),
            component(9, 9.0, 1),
        ],
    )


class FakeApi:
    """Steuert die gepatchten Client-Methoden pro Test."""

    def __init__(self) -> None:
        self.stations: dict[str, StationMeta] | Exception = dict(DEFAULT_STATIONS)
        self.air: dict[str, StationAirQuality | Exception] = {
            "1117": bonn_air(),
            "1114": koeln_air(),
        }
        # Antworten für das lange Rückblick-Fenster; ohne Eintrag gilt ``air``.
        self.history: dict[str, StationAirQuality | Exception] = {}
        self.stations_hours_back: int | None = None
        self.air_calls: list[tuple[str, int]] = []

    async def get_stations(self, *, hours_back: int) -> dict[str, StationMeta]:
        self.stations_hours_back = hours_back
        if isinstance(self.stations, Exception):
            raise self.stations
        return self.stations

    async def get_air(self, station_id: str, *, hours_back: int) -> StationAirQuality:
        self.air_calls.append((str(station_id), hours_back))
        result = self.air.get(str(station_id))
        if hours_back > FETCH_WINDOW_HOURS and str(station_id) in self.history:
            result = self.history[str(station_id)]
        if isinstance(result, Exception):
            raise result
        if result is None:
            return air(str(station_id), [])
        return result


@pytest.fixture(autouse=True)
def auto_enable_custom_integrations(enable_custom_integrations):
    """Custom integrations für alle Tests aktivieren."""
    return


@pytest.fixture
def fake_api():
    """Patch the API client with controllable fake data."""
    api = FakeApi()
    with (
        patch.object(UbaLqiApiClient, "async_get_stations", side_effect=api.get_stations),
        patch.object(UbaLqiApiClient, "async_get_air_quality", side_effect=api.get_air),
    ):
        yield api


def entry_data_v2() -> dict:
    return {
        "location_source": "home",
        "latitude": HOME_LAT,
        "longitude": HOME_LON,
        "radius_km": 50,
        "stations": {
            "1117": {
                "code": "DENW062",
                "name": "Bonn-Auerberg",
                "city": "Bonn",
                "latitude": 50.7536,
                "longitude": 7.0826,
                "setting": "vorstädtisches Gebiet",
                "station_type": "Hintergrund",
                "distance_km": 2.68,
                "components": [1, 5, 9],
            },
            "1114": {
                "code": "DENW059",
                "name": "Köln-Rodenkirchen",
                "city": "Köln",
                "latitude": 50.8942,
                "longitude": 6.9910,
                "setting": "vorstädtisches Gebiet",
                "station_type": "Hintergrund",
                "distance_km": 19.55,
                "components": [1, 3, 4, 5, 9],
            },
        },
    }


@pytest.fixture
def config_entry(hass) -> MockConfigEntry:
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="Bonn-Auerberg, Köln-Rodenkirchen",
        data=entry_data_v2(),
        options={},
        version=2,
        entry_id="test_entry",
    )
    entry.add_to_hass(hass)
    return entry


@pytest.fixture
def frozen_now(freezer):
    freezer.move_to(NOW_UTC)
    return NOW_UTC
