"""Tests for setup, unload, migration and registry cleanup.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.config_entries import ConfigEntryState
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr, entity_registry as er
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.uba_lqi.api import UbaLqiConnectionError
from custom_components.uba_lqi.const import DOMAIN

from .conftest import HOME_LAT, HOME_LON


async def test_setup_and_unload(hass: HomeAssistant, fake_api, config_entry) -> None:
    assert await hass.config_entries.async_setup(config_entry.entry_id)
    await hass.async_block_till_done()
    assert config_entry.state is ConfigEntryState.LOADED

    assert await hass.config_entries.async_unload(config_entry.entry_id)
    await hass.async_block_till_done()
    assert config_entry.state is ConfigEntryState.NOT_LOADED


async def test_setup_retries_when_api_down(
    hass: HomeAssistant, fake_api, config_entry
) -> None:
    fake_api.air = {
        "1117": UbaLqiConnectionError("down"),
        "1114": UbaLqiConnectionError("down"),
    }
    assert not await hass.config_entries.async_setup(config_entry.entry_id)
    await hass.async_block_till_done()
    assert config_entry.state is ConfigEntryState.SETUP_RETRY


async def test_migration_from_v1(hass: HomeAssistant, fake_api) -> None:
    """Alte Q14siX-Einträge werden auf das neue Schema migriert."""
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="UBA Luftqualitätsindex (LQI) (2 Stationen)",
        version=1,
        data={
            "location_source": "home",
            "latitude": HOME_LAT,
            "longitude": HOME_LON,
            "search_radius_km": 75,
            "max_candidates": 20,
            "scan_interval_minutes": 5,
            "selected_stations": ["1117", "1114"],
            "station_details": {
                "1117": {
                    "station_id": "1117",
                    "code": "DENW062",
                    "name": "Bonn-Auerberg",
                    "city": "Bonn",
                    "latitude": 50.7536,
                    "longitude": 7.0826,
                    "station_setting_name": "vorstädtisches Gebiet",
                    "station_type_name": "Hintergrund",
                },
                "1114": {
                    "station_id": "1114",
                    "code": "DENW059",
                    "name": "Köln-Rodenkirchen",
                    "city": "Köln",
                    "latitude": 50.8942,
                    "longitude": 6.9910,
                    "station_setting_name": "vorstädtisches Gebiet",
                    "station_type_name": "Hintergrund",
                },
            },
            "component_details": {"1": {"code": "PM10"}},
        },
    )
    entry.add_to_hass(hass)

    assert await hass.config_entries.async_setup(entry.entry_id)
    await hass.async_block_till_done()

    assert entry.version == 2
    assert entry.state is ConfigEntryState.LOADED
    stations = entry.data["stations"]
    assert list(stations) == ["1117", "1114"]  # nach Entfernung sortiert
    assert stations["1117"]["distance_km"] is not None
    # Komponenten wurden beim ersten Setup einmalig per API ermittelt.
    assert stations["1117"]["components"] == [1, 5, 9]
    assert stations["1114"]["components"] == [1, 3, 4, 5, 9]
    # Zu kurze Intervalle werden auf das Minimum angehoben.
    assert entry.options["update_interval_minutes"] == 15
    assert "component_details" not in entry.data


async def test_stale_registry_cleanup(
    hass: HomeAssistant, fake_api, config_entry
) -> None:
    """Geräte/Entitäten entfernter Stationen und alte unique_ids verschwinden."""
    device_registry = dr.async_get(hass)
    stale_device = device_registry.async_get_or_create(
        config_entry_id=config_entry.entry_id,
        identifiers={(DOMAIN, "999")},
        name="Alte Station",
    )
    entity_registry = er.async_get(hass)
    entity_registry.async_get_or_create(
        "sensor",
        DOMAIN,
        "1117_lqi_label",  # Schema der Version 1
        config_entry=config_entry,
    )

    assert await hass.config_entries.async_setup(config_entry.entry_id)
    await hass.async_block_till_done()

    assert device_registry.async_get(stale_device.id) is None
    assert (
        entity_registry.async_get_entity_id("sensor", DOMAIN, "1117_lqi_label") is None
    )
    # Die neuen Entitäten existieren.
    assert entity_registry.async_get_entity_id("sensor", DOMAIN, "1117_lqi")
