"""Tests for the v4 API client parsing.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from datetime import UTC, datetime

from homeassistant.helpers.aiohttp_client import async_get_clientsession
import pytest

from custom_components.uba_lqi.api import (
    UbaLqiApiClient,
    UbaLqiConnectionError,
    UbaLqiResponseError,
)

AIRQUALITY_URL = (
    "https://luftdaten.umweltbundesamt.de/api/air-data/v4/airquality/json"
)
META_URL = "https://luftdaten.umweltbundesamt.de/api/air-data/v4/meta/json"


def airquality_payload() -> dict:
    """Echtes v4-Antwortformat, Zeiten in MEZ (UTC+1)."""
    return {
        "request": {},
        "indices": {},
        "count": 1,
        "data": {
            "1117": {
                # Ältere Stunde: NO2 vorhanden ("hinkende" Komponente).
                "2026-08-07 05:00:00": [
                    "2026-08-07 06:00:00",
                    1,
                    0,
                    [1, 21, 1, "1.1"],
                    [5, 15, 1, "1.2"],
                    [9, 12, 1, "1.5"],
                ],
                # Jüngste Stunde: NO2 fehlt, Gesamtindex 0 ist gültig.
                "2026-08-07 06:00:00": [
                    "2026-08-07 07:00:00",
                    0,
                    1,
                    [1, 8, 0, "0.9"],
                    [9, 4, 0, "0.8"],
                ],
            }
        },
    }


async def test_airquality_parsing(hass, aioclient_mock, frozen_now) -> None:
    """Zeitzone, Index 0 und hinkende Komponenten werden korrekt behandelt."""
    aioclient_mock.get(AIRQUALITY_URL, json=airquality_payload())
    client = UbaLqiApiClient(async_get_clientsession(hass))
    air = await client.async_get_air_quality("1117", hours_back=24)

    # MEZ 06:00 -> UTC 05:00.
    assert air.newest_start == datetime(2026, 8, 7, 5, 0, tzinfo=UTC)
    assert air.newest_end == datetime(2026, 8, 7, 6, 0, tzinfo=UTC)
    # Gesamtindex 0 ("sehr gut") ist ein Wert, kein Fehlen.
    assert air.total_index == 0
    assert air.all_components_reported is False

    # PM10/PM2,5 aus der jüngsten Stunde.
    assert air.components[1].value == 8
    assert air.components[1].index == 0
    # NO2 stammt aus der älteren Stunde und geht nicht verloren.
    assert air.components[5].value == 15
    assert air.components[5].end == datetime(2026, 8, 7, 5, 0, tzinfo=UTC)

    # Das Abfragefenster wird in MEZ gerechnet: 06:30 UTC = 07:30 MEZ,
    # 24 h zurück -> 06.08. als date_from.
    query = aioclient_mock.mock_calls[-1][1].query
    assert query["station"] == "1117"
    assert query["date_from"] == "2026-08-06"
    assert query["date_to"] == "2026-08-07"
    assert query["time_from"] == "1"
    assert query["time_to"] == "24"


async def test_airquality_invalid_index(hass, aioclient_mock, frozen_now) -> None:
    """-1 und unsinnige Indexwerte werden zu None."""
    payload = airquality_payload()
    payload["data"]["1117"] = {
        "2026-08-07 06:00:00": [
            "2026-08-07 07:00:00",
            -1,
            1,
            [1, 8, -1, "0.9"],
            [5, None, 7, None],
        ]
    }
    aioclient_mock.get(AIRQUALITY_URL, json=payload)
    client = UbaLqiApiClient(async_get_clientsession(hass))
    air = await client.async_get_air_quality("1117", hours_back=24)

    assert air.total_index is None
    assert air.components[1].index is None
    assert air.components[1].value == 8
    assert air.components[5].index is None
    assert air.components[5].value is None


async def test_airquality_empty(hass, aioclient_mock, frozen_now) -> None:
    """Keine Daten -> leeres, aber gültiges Ergebnis."""
    aioclient_mock.get(AIRQUALITY_URL, json={"data": {}})
    client = UbaLqiApiClient(async_get_clientsession(hass))
    air = await client.async_get_air_quality("1117", hours_back=24)
    assert air.components == {}
    assert air.newest_end is None
    assert air.total_index is None


async def test_station_meta_parsing(hass, aioclient_mock, frozen_now) -> None:
    """Stationsliste im positionsbasierten v4-Format."""
    aioclient_mock.get(
        META_URL,
        json={
            "stations": {
                "1117": [
                    "1117",
                    "DENW062",
                    "Bonn-Auerberg",
                    "Bonn",
                    "",
                    "1986-12-01",
                    None,
                    "7.0826",
                    "50.7536",
                    "10",
                    "2",
                    "1",
                    "NW",
                    "Nordrhein-Westfalen",
                    "vorstädtisches Gebiet",
                    "vorstädtisch",
                    "Hintergrund",
                    "An der Josefshöhe",
                    "",
                    "53117",
                ]
            },
            "components": {},
        },
    )
    client = UbaLqiApiClient(async_get_clientsession(hass))
    stations = await client.async_get_stations(hours_back=14 * 24)
    # Fenster in MEZ: 07.08. 07:30 minus 14 Tage.
    request_url = aioclient_mock.mock_calls[-1][1]
    assert request_url.query["date_from"] == "2026-07-24"
    assert request_url.query["date_to"] == "2026-08-07"
    station = stations["1117"]
    assert station.code == "DENW062"
    assert station.name == "Bonn-Auerberg"
    assert station.latitude == 50.7536
    assert station.longitude == 7.0826
    assert station.setting == "vorstädtisches Gebiet"
    assert station.station_type == "Hintergrund"


async def test_malformed_rows_are_skipped(hass, aioclient_mock, frozen_now) -> None:
    """Kaputte Zeilen/Komponenten aus der API stören das Parsen nicht."""
    payload = {
        "data": {
            "1117": {
                "kein-datum": ["2026-08-07 07:00:00", 1, 0],
                "2026-08-07 05:00:00": "keine-liste",
                "2026-08-07 06:00:00": [
                    None,  # fehlendes Ende -> Start + 1 h
                    "x",  # unlesbarer Gesamtindex -> None
                    "y",  # unlesbares incomplete -> None
                    "keine-liste",
                    [None, 1, 1],  # Komponente ohne ID
                    [1, 8, 0, "0.9"],
                    [1, 7, 0, "0.8"],  # gleiche Komponente, nicht neuer
                ],
            }
        }
    }
    aioclient_mock.get(AIRQUALITY_URL, json=payload)
    client = UbaLqiApiClient(async_get_clientsession(hass))
    air = await client.async_get_air_quality("1117", hours_back=24)

    assert set(air.components) == {1}
    assert air.components[1].value == 8
    assert air.total_index is None
    assert air.all_components_reported is None
    # Fallback-Ende: Start 06:00 MEZ + 1 h = 06:00 UTC.
    assert air.components[1].end == datetime(2026, 8, 7, 6, 0, tzinfo=UTC)


async def test_station_list_unparseable(hass, aioclient_mock, frozen_now) -> None:
    """Nur unbrauchbare Stations-Einträge -> Fehler statt leerer Liste."""
    aioclient_mock.get(
        META_URL,
        json={
            "stations": {
                "1": ["1", "C"],
                "2": ["2", "C", None, "Ort", "", None, None, "7.0", "50.0"],
            }
        },
    )
    client = UbaLqiApiClient(async_get_clientsession(hass))
    with pytest.raises(UbaLqiResponseError):
        await client.async_get_stations(hours_back=24)


async def test_http_error(hass, aioclient_mock, frozen_now) -> None:
    aioclient_mock.get(AIRQUALITY_URL, status=503)
    client = UbaLqiApiClient(async_get_clientsession(hass))
    with pytest.raises(UbaLqiConnectionError):
        await client.async_get_air_quality("1117", hours_back=24)


async def test_timeout(hass, aioclient_mock, frozen_now) -> None:
    aioclient_mock.get(AIRQUALITY_URL, exc=TimeoutError())
    client = UbaLqiApiClient(async_get_clientsession(hass))
    with pytest.raises(UbaLqiConnectionError):
        await client.async_get_air_quality("1117", hours_back=24)


async def test_invalid_json(hass, aioclient_mock, frozen_now) -> None:
    aioclient_mock.get(META_URL, text="kein json")
    client = UbaLqiApiClient(async_get_clientsession(hass))
    with pytest.raises(UbaLqiResponseError):
        await client.async_get_stations(hours_back=24)


async def test_missing_station_list(hass, aioclient_mock, frozen_now) -> None:
    aioclient_mock.get(META_URL, json={"stations": None})
    client = UbaLqiApiClient(async_get_clientsession(hass))
    with pytest.raises(UbaLqiResponseError):
        await client.async_get_stations(hours_back=24)


async def test_unexpected_payload(hass, aioclient_mock, frozen_now) -> None:
    aioclient_mock.get(META_URL, json=[])
    client = UbaLqiApiClient(async_get_clientsession(hass))
    with pytest.raises(UbaLqiResponseError):
        await client.async_get_stations(hours_back=24)
