"""Tests for coordinator backoff, partial failures and repair issues.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from datetime import timedelta

from homeassistant.core import HomeAssistant
from homeassistant.helpers import issue_registry as ir
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.uba_lqi.api import UbaLqiConnectionError
from custom_components.uba_lqi.const import DOMAIN

from .conftest import FRESH_END, air, bonn_air, component, entry_data_v2, koeln_air


async def _setup(hass, config_entry):
    assert await hass.config_entries.async_setup(config_entry.entry_id)
    await hass.async_block_till_done()
    return config_entry.runtime_data


async def test_backoff_on_failure_and_reset(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Fehlerfall: Intervall verdoppelt sich (Deckel 6 h), Erfolg setzt zurück."""
    coordinator = await _setup(hass, config_entry)
    base = timedelta(minutes=60)
    assert coordinator.update_interval == base

    fake_api.air = {
        "1117": UbaLqiConnectionError("down"),
        "1114": UbaLqiConnectionError("down"),
    }
    await coordinator.async_refresh()
    assert coordinator.last_update_success is False
    assert coordinator.update_interval == base * 2

    await coordinator.async_refresh()
    assert coordinator.update_interval == base * 4

    for _ in range(4):
        await coordinator.async_refresh()
    assert coordinator.update_interval == timedelta(hours=6)

    fake_api.air = {"1117": bonn_air(), "1114": koeln_air()}
    await coordinator.async_refresh()
    assert coordinator.last_update_success is True
    assert coordinator.update_interval == base


async def test_partial_failure_keeps_other_station(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Fällt eine Station aus, bleibt die andere nutzbar — kein UpdateFailed."""
    coordinator = await _setup(hass, config_entry)
    fake_api.air = {
        "1117": UbaLqiConnectionError("down"),
        "1114": koeln_air(),
    }
    await coordinator.async_refresh()
    assert coordinator.last_update_success is True
    # Transienter Fehler: letzter bekannter Stand von 1117 bleibt erhalten,
    # die Frische-Grenze altert ihn von selbst aus.
    assert coordinator.data.stations["1117"].air is not None
    assert coordinator.data.stations["1117"].lqi == 1
    assert coordinator.data.stations["1117"].last_measurement == FRESH_END
    assert coordinator.data.stations["1114"].lqi == 2
    assert coordinator.data.aggregate.lqi == 2
    # Backoff greift bei Teilerfolg nicht.
    assert coordinator.update_interval == timedelta(minutes=60)


async def test_partial_failure_without_history_is_unavailable(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Fehler ohne früheren Erfolg: Station bleibt ohne Daten."""
    fake_api.air = {
        "1117": UbaLqiConnectionError("down"),
        "1114": koeln_air(),
    }
    coordinator = await _setup(hass, config_entry)
    assert coordinator.data.stations["1117"].air is None
    assert coordinator.data.stations["1117"].lqi is None
    assert coordinator.data.stations["1114"].lqi == 2


async def test_repair_issue_for_silent_station(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Station ohne Daten seit > 24 h erzeugt ein Repair Issue, Erholung löscht es."""
    fake_api.air["1117"] = air("1117", [])
    coordinator = await _setup(hass, config_entry)

    registry = ir.async_get(hass)
    issue = registry.async_get_issue(DOMAIN, "station_silent_1117")
    assert issue is not None
    assert issue.severity == ir.IssueSeverity.WARNING

    fake_api.air["1117"] = bonn_air()
    await coordinator.async_refresh()
    assert registry.async_get_issue(DOMAIN, "station_silent_1117") is None


async def test_aggregate_prefers_nearest_station_per_component(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """PM ist lokal: Der kombinierte Index nimmt PM aus Bonn, nicht aus Köln."""
    fake_api.air["1114"] = air(
        "1114", [component(1, 80.0, 3), component(3, 40.0, 1)]
    )
    coordinator = await _setup(hass, config_entry)

    aggregate = coordinator.data.aggregate
    # PM10 kommt aus Bonn (Index 1), Kölns PM10 (Index 3) wird ignoriert.
    station_id, value = aggregate.components[1]
    assert station_id == "1117"
    assert value.index == 1
    assert aggregate.lqi == 1


async def test_aggregate_sorts_stations_by_distance(
    hass: HomeAssistant, fake_api, frozen_now
) -> None:
    """Fernere Station zuerst gespeichert: die nähere gewinnt trotzdem."""
    data = entry_data_v2()
    stations = data["stations"]
    data["stations"] = {"1114": stations["1114"], "1117": stations["1117"]}
    entry = MockConfigEntry(
        domain=DOMAIN, data=data, options={}, version=2, entry_id="swapped_entry"
    )
    entry.add_to_hass(hass)
    fake_api.air["1117"] = air("1117", [component(1, 45.0, 2)])
    coordinator = await _setup(hass, entry)

    aggregate = coordinator.data.aggregate
    # PM10 kommt aus Bonn (2,68 km, Index 2), nicht aus Köln (19,55 km).
    station_id, value = aggregate.components[1]
    assert station_id == "1117"
    assert value.index == 2
    assert aggregate.lqi == 2
    assert aggregate.driver_station == "1117"
    assert aggregate.driver_component == 1


async def test_aggregate_without_distances_keeps_stored_order(
    hass: HomeAssistant, fake_api, frozen_now
) -> None:
    """Ohne bekannte Entfernungen entscheidet die Speicher-Reihenfolge."""
    data = entry_data_v2()
    data["latitude"] = None
    data["longitude"] = None
    stations = data["stations"]
    data["stations"] = {
        "1114": {**stations["1114"], "distance_km": None},
        "1117": {**stations["1117"], "distance_km": None},
    }
    entry = MockConfigEntry(
        domain=DOMAIN, data=data, options={}, version=2, entry_id="no_distance_entry"
    )
    entry.add_to_hass(hass)
    coordinator = await _setup(hass, entry)

    # Köln ist zuerst gespeichert und liefert PM10 daher als Quelle.
    assert coordinator.data.aggregate.components[1][0] == "1114"
