"""Tests for the sensor platform.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.const import (
    CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
    CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.uba_lqi.const import DOMAIN

from .conftest import STALE_END, air, component


async def _setup(hass, config_entry):
    assert await hass.config_entries.async_setup(config_entry.entry_id)
    await hass.async_block_till_done()


def _state(hass, unique_id):
    entity_id = er.async_get(hass).async_get_entity_id("sensor", DOMAIN, unique_id)
    assert entity_id, f"entity {unique_id} not registered"
    return hass.states.get(entity_id)


async def test_station_and_combined_lqi(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Der Ozon-Fall: Bonn „gut", Köln wegen O3 „mäßig" — kombiniert „mäßig"."""
    await _setup(hass, config_entry)

    bonn = _state(hass, "1117_lqi")
    assert bonn.state == "good"
    assert bonn.attributes["worst_component"] == "pm10"
    assert bonn.attributes["all_components_reported"] is True

    koeln = _state(hass, "1114_lqi")
    assert koeln.state == "moderate"
    assert koeln.attributes["worst_component"] == "o3"

    combined = _state(hass, "test_entry_combined_lqi")
    assert combined.state == "moderate"
    assert combined.attributes["worst_component"] == "o3"
    assert combined.attributes["worst_component_station"] == "Köln-Rodenkirchen"
    # Je Komponente gewinnt die nächstgelegene Station: PM10 kommt aus Bonn.
    assert combined.attributes["components"]["pm10"]["station"] == "Bonn-Auerberg"
    assert combined.attributes["components"]["o3"]["station"] == "Köln-Rodenkirchen"


async def test_index_zero_is_very_good(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Index 0 ist „sehr gut" — nicht „unbekannt"."""
    fake_api.air["1117"] = air("1117", [component(1, 5.0, 0), component(9, 3.0, 0)])
    fake_api.air["1114"] = air("1114", [component(3, 20.0, 0)])
    await _setup(hass, config_entry)

    assert _state(hass, "1117_lqi").state == "very_good"
    assert _state(hass, "test_entry_combined_lqi").state == "very_good"


async def test_stale_values_become_unavailable(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Werte älter als 3 h -> unavailable; letzte Messung bleibt sichtbar."""
    fake_api.air["1117"] = air(
        "1117", [component(1, 20.0, 1, end=STALE_END)]
    )
    await _setup(hass, config_entry)

    assert _state(hass, "1117_lqi").state == "unavailable"
    assert _state(hass, "1117_component_1").state == "unavailable"
    # Der Zeitpunkt der letzten Messung bleibt als Diagnose sichtbar.
    assert _state(hass, "1117_last_measurement").state == STALE_END.isoformat()
    # Köln liefert weiter — der kombinierte Index bleibt nutzbar.
    assert _state(hass, "test_entry_combined_lqi").state == "moderate"


async def test_lagging_component_stays_available(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """NO2 hinkt eine Stunde hinterher, bleibt aber verfügbar (< 3 h)."""
    await _setup(hass, config_entry)
    no2 = _state(hass, "1117_component_5")
    assert no2.state == "15.0"
    assert no2.attributes["index"] == 1
    assert no2.attributes["level"] == "good"


async def test_entities_from_stored_metadata(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Entitäten entstehen aus den Metadaten, nicht aus der ersten Antwort."""
    # Erste Antwort enthält nur PM10 — NO2/PM2,5 fehlen gerade.
    fake_api.air["1117"] = air("1117", [component(1, 20.0, 1)])
    await _setup(hass, config_entry)

    registry = er.async_get(hass)
    for unique_id in ("1117_component_1", "1117_component_5", "1117_component_9"):
        assert registry.async_get_entity_id("sensor", DOMAIN, unique_id), unique_id
    # Fehlende Komponente ist unavailable, existiert aber.
    assert _state(hass, "1117_component_5").state == "unavailable"


async def test_component_units_and_device_classes(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    await _setup(hass, config_entry)
    pm10 = _state(hass, "1117_component_1")
    assert (
        pm10.attributes["unit_of_measurement"]
        == CONCENTRATION_MICROGRAMS_PER_CUBIC_METER
    )
    assert pm10.attributes["device_class"] == "pm10"
    o3 = _state(hass, "1114_component_3")
    assert o3.attributes["device_class"] == "ozone"
    assert o3.attributes["state_class"] == "measurement"


async def test_numeric_sensors_when_enabled(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    """Die per Default deaktivierten numerischen Sensoren liefern 0-4."""
    registry = er.async_get(hass)
    registry.async_get_or_create(
        "sensor", DOMAIN, "1117_lqi_numeric", config_entry=config_entry
    )
    registry.async_get_or_create(
        "sensor",
        DOMAIN,
        "test_entry_combined_lqi_numeric",
        config_entry=config_entry,
    )
    await _setup(hass, config_entry)

    assert _state(hass, "1117_lqi_numeric").state == "1"
    assert _state(hass, "test_entry_combined_lqi_numeric").state == "2"


async def test_co_sensor_uses_native_unit(
    hass: HomeAssistant, fake_api, frozen_now
) -> None:
    """CO: Geräteklasse mit mg/m³ (nativ erlaubt), kein Index."""
    entry = MockConfigEntry(
        domain=DOMAIN,
        title="CO-Station",
        version=2,
        entry_id="co_entry",
        data={
            "location_source": "home",
            "latitude": 50.73,
            "longitude": 7.09,
            "radius_km": 50,
            "stations": {
                "9999": {
                    "code": "DETEST1",
                    "name": "Teststation",
                    "city": "Testtown",
                    "latitude": 50.7,
                    "longitude": 7.0,
                    "setting": None,
                    "station_type": None,
                    "distance_km": 5.0,
                    "components": [1, 2],
                }
            },
        },
    )
    entry.add_to_hass(hass)
    fake_api.air["9999"] = air(
        "9999", [component(1, 12.0, 1), component(2, 0.3, None)]
    )
    await _setup(hass, entry)

    co = _state(hass, "9999_component_2")
    assert co.state == "0.3"
    assert co.attributes["device_class"] == "carbon_monoxide"
    assert (
        co.attributes["unit_of_measurement"]
        == CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER
    )
    # CO ist keine Indexkomponente - kein Level, aber verfügbar.
    assert co.attributes["index"] is None
    assert co.attributes["level"] is None
