"""Tests for the diagnostics output.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.core import HomeAssistant

from custom_components.uba_lqi.diagnostics import async_get_config_entry_diagnostics


async def test_diagnostics_redacts_home_location(
    hass: HomeAssistant, fake_api, config_entry, frozen_now
) -> None:
    assert await hass.config_entries.async_setup(config_entry.entry_id)
    await hass.async_block_till_done()

    diagnostics = await async_get_config_entry_diagnostics(hass, config_entry)

    # Heimkoordinaten werden geschwärzt.
    assert diagnostics["entry"]["data"]["latitude"] == "**REDACTED**"
    assert diagnostics["entry"]["data"]["longitude"] == "**REDACTED**"

    assert diagnostics["update"]["last_update_success"] is True
    assert diagnostics["stations"]["1117"]["lqi"] == 1
    assert diagnostics["stations"]["1114"]["lqi"] == 2
    assert diagnostics["aggregate"]["lqi"] == 2
    assert diagnostics["aggregate"]["driver_station"] == "1114"
    # Vollständig JSON-serialisierbar.
    import json

    json.dumps(diagnostics)
