"""Tests for the config, options and reconfigure flows.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from datetime import timedelta

from homeassistant import config_entries
from homeassistant.core import HomeAssistant
from homeassistant.data_entry_flow import FlowResultType

from custom_components.uba_lqi.api import UbaLqiConnectionError
from custom_components.uba_lqi.const import DISCOVERY_WINDOW_HOURS, DOMAIN

from .conftest import HOME_LAT, HOME_LON


async def _start_flow(hass: HomeAssistant):
    return await hass.config_entries.flow.async_init(
        DOMAIN, context={"source": config_entries.SOURCE_USER}
    )


async def test_full_flow_home_location(hass: HomeAssistant, fake_api) -> None:
    """Happy Path: Home-Standort, zwei Stationen, Komponenten-Ermittlung."""
    hass.config.latitude = HOME_LAT
    hass.config.longitude = HOME_LON

    result = await _start_flow(hass)
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "user"

    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "home", "radius_km": 50},
    )
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "select_stations"
    # Karlsruhe liegt außerhalb des Radius.
    assert result["description_placeholders"]["count"] == "2"

    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"stations": ["1117", "1114"]},
    )
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert result["title"] == "Bonn-Auerberg, Köln-Rodenkirchen"

    stations = result["data"]["stations"]
    # Nach Entfernung sortiert: Bonn zuerst.
    assert list(stations) == ["1117", "1114"]
    # Komponenten wurden über das 48-h-Fenster ermittelt und gespeichert.
    assert stations["1117"]["components"] == [1, 5, 9]
    assert stations["1114"]["components"] == [1, 3, 4, 5, 9]
    assert stations["1117"]["distance_km"] < stations["1114"]["distance_km"]
    # Großzügiges Fenster, damit die Einrichtung auch bei einem Datenausfall gelingt.
    assert fake_api.stations_hours_back == DISCOVERY_WINDOW_HOURS
    assert {
        ("1117", DISCOVERY_WINDOW_HOURS),
        ("1114", DISCOVERY_WINDOW_HOURS),
    } <= set(fake_api.air_calls)


async def test_manual_location(hass: HomeAssistant, fake_api) -> None:
    result = await _start_flow(hass)
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "manual", "radius_km": 30},
    )
    assert result["step_id"] == "manual_location"

    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location": {"latitude": HOME_LAT, "longitude": HOME_LON}},
    )
    assert result["step_id"] == "select_stations"

    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"stations": ["1117"]}
    )
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert result["data"]["latitude"] == HOME_LAT
    assert list(result["data"]["stations"]) == ["1117"]


async def test_cannot_connect(hass: HomeAssistant, fake_api) -> None:
    fake_api.stations = UbaLqiConnectionError("down")
    result = await _start_flow(hass)
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "manual", "radius_km": 50},
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location": {"latitude": HOME_LAT, "longitude": HOME_LON}},
    )
    assert result["type"] is FlowResultType.FORM
    assert result["errors"] == {"base": "cannot_connect"}


async def test_no_stations_in_radius(hass: HomeAssistant, fake_api) -> None:
    result = await _start_flow(hass)
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "manual", "radius_km": 5},
    )
    # Standort fernab aller Stationen.
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location": {"latitude": 54.5, "longitude": 13.4}},
    )
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "user"
    assert result["errors"] == {"base": "no_stations_found"}


async def test_station_overlap_rejected(
    hass: HomeAssistant, fake_api, config_entry
) -> None:
    """Eine Station darf nur zu einem Eintrag gehören (eindeutige Geräte)."""
    result = await _start_flow(hass)
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "manual", "radius_km": 50},
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location": {"latitude": HOME_LAT, "longitude": HOME_LON}},
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"stations": ["1117"]}
    )
    assert result["type"] is FlowResultType.FORM
    assert result["errors"] == {"stations": "station_already_configured"}


async def test_empty_selection_rejected(hass: HomeAssistant, fake_api) -> None:
    """Leere Auswahl -> Fehler, Formular bleibt offen."""
    result = await _start_flow(hass)
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "manual", "radius_km": 50},
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location": {"latitude": HOME_LAT, "longitude": HOME_LON}},
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"stations": []}
    )
    assert result["type"] is FlowResultType.FORM
    assert result["errors"] == {"stations": "no_station_selected"}


async def test_cannot_connect_during_finish(hass: HomeAssistant, fake_api) -> None:
    """API-Ausfall bei der Komponenten-Ermittlung -> Fehler statt Absturz."""
    result = await _start_flow(hass)
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "manual", "radius_km": 50},
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location": {"latitude": HOME_LAT, "longitude": HOME_LON}},
    )
    fake_api.air["1117"] = UbaLqiConnectionError("down")
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"stations": ["1117", "1114"]}
    )
    assert result["type"] is FlowResultType.FORM
    assert result["errors"] == {"base": "cannot_connect"}
    # Die Auswahl des Nutzers bleibt nach dem Fehler erhalten.
    defaults = result["data_schema"]({})
    assert set(defaults["stations"]) == {"1117", "1114"}


async def test_reconfigure(hass: HomeAssistant, fake_api, config_entry) -> None:
    """Reconfigure ersetzt die Stationsauswahl im bestehenden Eintrag."""
    result = await config_entry.start_reconfigure_flow(hass)
    assert result["step_id"] == "user"

    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location_source": "manual", "radius_km": 50},
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        {"location": {"latitude": HOME_LAT, "longitude": HOME_LON}},
    )
    assert result["step_id"] == "select_stations"

    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"stations": ["1117"]}
    )
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "reconfigure_successful"
    assert list(config_entry.data["stations"]) == ["1117"]
    # Der Reload läuft im Hintergrund; abwarten, sonst bleibt der
    # Coordinator-Timer über das Testende hinaus stehen.
    await hass.async_block_till_done()


async def test_options_flow(hass: HomeAssistant, fake_api, config_entry) -> None:
    await hass.config_entries.async_setup(config_entry.entry_id)
    await hass.async_block_till_done()

    result = await hass.config_entries.options.async_init(config_entry.entry_id)
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "init"

    result = await hass.config_entries.options.async_configure(
        result["flow_id"], {"update_interval_minutes": 30}
    )
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert config_entry.options == {"update_interval_minutes": 30}

    # Nach dem Reload läuft der Coordinator tatsächlich mit dem neuen Intervall.
    await hass.async_block_till_done()
    assert config_entry.runtime_data.update_interval == timedelta(minutes=30)
